### ISSUE TITLE
Range or index out of bounds

### ISSUE THREAD

**Issue by MohammadSh** [DevZaid/GDSLink#1]
when run this code , this exception is Appear , why ?
<img width="771" alt="screen shot 2016-09-24 at 12 26 47 am" src="https://cloud.githubusercontent.com/assets/9326018/18801787/9f536302-81ed-11e6-9d1a-a2ce8a458d86.png">

**Comment by zaidfadhil** [comment]
i pushed an update to the code ... you can try it now

**Comment by MohammadAyman** [comment]
it's run , Thank you a lot

**Comment by zaidfadhil** [comment]
you are welcome :)
